/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "examples/fifo_sync/fifo_sync.sv:1.1-74.10" *)
module fifo_sync(clk, rst, wr_en, rd_en, data_in, data_out, full, empty, count);
  (* src = "examples/fifo_sync/fifo_sync.sv:6.35-6.38" *)
  input clk;
  wire clk;
  (* src = "examples/fifo_sync/fifo_sync.sv:7.35-7.38" *)
  input rst;
  wire rst;
  (* src = "examples/fifo_sync/fifo_sync.sv:8.35-8.40" *)
  input wr_en;
  wire wr_en;
  (* src = "examples/fifo_sync/fifo_sync.sv:9.35-9.40" *)
  input rd_en;
  wire rd_en;
  (* src = "examples/fifo_sync/fifo_sync.sv:10.35-10.42" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "examples/fifo_sync/fifo_sync.sv:11.35-11.43" *)
  output [7:0] data_out;
  reg [7:0] data_out;
  (* src = "examples/fifo_sync/fifo_sync.sv:12.35-12.39" *)
  output full;
  wire full;
  (* src = "examples/fifo_sync/fifo_sync.sv:13.35-13.40" *)
  output empty;
  wire empty;
  (* src = "examples/fifo_sync/fifo_sync.sv:14.35-14.40" *)
  output [4:0] count;
  reg [4:0] count;
  (* src = "examples/fifo_sync/fifo_sync.sv:29.5-72.8" *)
  wire [7:0] _000_;
  (* src = "examples/fifo_sync/fifo_sync.sv:29.5-72.8" *)
  wire [7:0] _001_;
  (* src = "examples/fifo_sync/fifo_sync.sv:29.5-72.8" *)
  wire [7:0] _002_;
  (* src = "examples/fifo_sync/fifo_sync.sv:29.5-72.8" *)
  wire [7:0] _003_;
  (* src = "examples/fifo_sync/fifo_sync.sv:29.5-72.8" *)
  wire [7:0] _004_;
  (* src = "examples/fifo_sync/fifo_sync.sv:29.5-72.8" *)
  wire [7:0] _005_;
  (* src = "examples/fifo_sync/fifo_sync.sv:29.5-72.8" *)
  wire [7:0] _006_;
  (* src = "examples/fifo_sync/fifo_sync.sv:29.5-72.8" *)
  wire [7:0] _007_;
  wire [7:0] _008_;
  (* src = "examples/fifo_sync/fifo_sync.sv:42.35-42.48" *)
  wire [3:0] _009_;
  (* src = "examples/fifo_sync/fifo_sync.sv:43.30-43.42" *)
  wire [4:0] _010_;
  (* src = "examples/fifo_sync/fifo_sync.sv:51.35-51.48" *)
  wire [3:0] _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire [7:0] _046_;
  (* src = "examples/fifo_sync/fifo_sync.sv:39.25-39.57" *)
  wire _047_;
  (* src = "examples/fifo_sync/fifo_sync.sv:48.25-48.57" *)
  wire _048_;
  (* src = "examples/fifo_sync/fifo_sync.sv:26.32-26.37" *)
  wire _049_;
  (* src = "examples/fifo_sync/fifo_sync.sv:27.32-27.38" *)
  wire _050_;
  wire [7:0] _051_;
  wire [7:0] _052_;
  wire [7:0] _053_;
  wire [7:0] _054_;
  wire [7:0] _055_;
  wire [7:0] _056_;
  wire [7:0] _057_;
  wire [7:0] _058_;
  wire [7:0] _059_;
  wire [7:0] _060_;
  wire [7:0] _061_;
  wire [7:0] _062_;
  wire [7:0] _063_;
  wire [7:0] _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire [3:0] _081_;
  wire [3:0] _082_;
  wire _083_;
  wire _084_;
  wire [3:0] _085_;
  wire [3:0] _086_;
  wire _087_;
  wire [4:0] _088_;
  (* src = "examples/fifo_sync/fifo_sync.sv:52.30-52.42" *)
  wire [4:0] _089_;
  (* src = "examples/fifo_sync/fifo_sync.sv:22.11-22.18" *)
  wire do_read;
  (* src = "examples/fifo_sync/fifo_sync.sv:21.11-21.19" *)
  wire do_write;
  reg [7:0] \mem[0] ;
  reg [7:0] \mem[10] ;
  reg [7:0] \mem[11] ;
  reg [7:0] \mem[12] ;
  reg [7:0] \mem[13] ;
  reg [7:0] \mem[14] ;
  reg [7:0] \mem[15] ;
  reg [7:0] \mem[1] ;
  reg [7:0] \mem[2] ;
  reg [7:0] \mem[3] ;
  reg [7:0] \mem[4] ;
  reg [7:0] \mem[5] ;
  reg [7:0] \mem[6] ;
  reg [7:0] \mem[7] ;
  reg [7:0] \mem[8] ;
  reg [7:0] \mem[9] ;
  (* src = "examples/fifo_sync/fifo_sync.sv:19.28-19.34" *)
  reg [3:0] rd_ptr;
  (* src = "examples/fifo_sync/fifo_sync.sv:18.28-18.34" *)
  reg [3:0] wr_ptr;
  always @(posedge clk)
    if (rst) data_out <= 8'h00;
    else if (_015_) data_out <= _008_;
  assign _010_ = count + (* src = "examples/fifo_sync/fifo_sync.sv:43.30-43.42" *) 1'h1;
  assign _009_ = wr_ptr + (* src = "examples/fifo_sync/fifo_sync.sv:62.35-62.48" *) 1'h1;
  assign _011_ = rd_ptr + (* src = "examples/fifo_sync/fifo_sync.sv:66.35-66.48" *) 1'h1;
  (* \always_ff  = 32'd1 *)
  (* src = "examples/fifo_sync/fifo_sync.sv:29.5-72.8" *)
  always @(posedge clk)
    if (rst) count <= 5'h00;
    else if (_012_) count <= _088_;
  (* \always_ff  = 32'd1 *)
  (* src = "examples/fifo_sync/fifo_sync.sv:29.5-72.8" *)
  always @(posedge clk)
    if (rst) wr_ptr <= 4'h0;
    else if (_013_) wr_ptr <= _086_;
  (* \always_ff  = 32'd1 *)
  (* src = "examples/fifo_sync/fifo_sync.sv:29.5-72.8" *)
  always @(posedge clk)
    if (rst) rd_ptr <= 4'h0;
    else if (_014_) rd_ptr <= _082_;
  always @(posedge clk)
    if (_065_) \mem[0]  <= _046_;
  always @(posedge clk)
    if (_072_) \mem[1]  <= _046_;
  always @(posedge clk)
    if (_073_) \mem[2]  <= _046_;
  always @(posedge clk)
    if (_074_) \mem[3]  <= _046_;
  always @(posedge clk)
    if (_075_) \mem[4]  <= _046_;
  always @(posedge clk)
    if (_076_) \mem[5]  <= _046_;
  always @(posedge clk)
    if (_077_) \mem[6]  <= _046_;
  always @(posedge clk)
    if (_078_) \mem[7]  <= _046_;
  always @(posedge clk)
    if (_079_) \mem[8]  <= _046_;
  always @(posedge clk)
    if (_080_) \mem[9]  <= _046_;
  always @(posedge clk)
    if (_066_) \mem[10]  <= _046_;
  always @(posedge clk)
    if (_067_) \mem[11]  <= _046_;
  always @(posedge clk)
    if (_068_) \mem[12]  <= _046_;
  always @(posedge clk)
    if (_069_) \mem[13]  <= _046_;
  always @(posedge clk)
    if (_070_) \mem[14]  <= _046_;
  always @(posedge clk)
    if (_071_) \mem[15]  <= _046_;
  assign _042_ = ~ wr_ptr[0];
  assign _043_ = ~ wr_ptr[1];
  assign _044_ = ~ wr_ptr[2];
  assign _045_ = ~ wr_ptr[3];
  assign _017_ = _042_ & _043_;
  assign _018_ = _044_ & _045_;
  assign _019_ = _017_ & _018_;
  assign _020_ = wr_ptr[0] & _043_;
  assign _021_ = _020_ & _018_;
  assign _022_ = _042_ & wr_ptr[1];
  assign _023_ = _022_ & _018_;
  assign _024_ = wr_ptr[0] & wr_ptr[1];
  assign _025_ = _024_ & _018_;
  assign _026_ = wr_ptr[2] & _045_;
  assign _027_ = _017_ & _026_;
  assign _028_ = _020_ & _026_;
  assign _029_ = _022_ & _026_;
  assign _030_ = _024_ & _026_;
  assign _031_ = _044_ & wr_ptr[3];
  assign _032_ = _017_ & _031_;
  assign _033_ = _020_ & _031_;
  assign _034_ = _022_ & _031_;
  assign _035_ = _024_ & _031_;
  assign _036_ = wr_ptr[2] & wr_ptr[3];
  assign _037_ = _017_ & _036_;
  assign _038_ = _020_ & _036_;
  assign _039_ = _022_ & _036_;
  assign _040_ = _024_ & _036_;
  assign _046_ = _003_[0] ? _002_ : _000_;
  assign _041_ = _001_[0] | _003_[0];
  assign _012_ = | { _084_, _087_ };
  assign _013_ = | { _083_, _087_ };
  assign _014_ = | { _084_, _083_ };
  assign _015_ = | { _084_, _083_ };
  assign _016_ = | { _087_, _083_ };
  assign full = count == (* src = "examples/fifo_sync/fifo_sync.sv:24.24-24.38" *) 5'h10;
  assign empty = ! (* src = "examples/fifo_sync/fifo_sync.sv:25.24-25.34" *) count;
  assign _047_ = wr_ptr == (* src = "examples/fifo_sync/fifo_sync.sv:59.25-59.57" *) 4'hf;
  assign _048_ = rd_ptr == (* src = "examples/fifo_sync/fifo_sync.sv:63.25-63.57" *) 4'hf;
  assign do_write = wr_en && (* src = "examples/fifo_sync/fifo_sync.sv:26.23-26.37" *) _049_;
  assign do_read = rd_en && (* src = "examples/fifo_sync/fifo_sync.sv:27.23-27.38" *) _050_;
  assign _049_ = ! (* src = "examples/fifo_sync/fifo_sync.sv:26.32-26.37" *) full;
  assign _050_ = ! (* src = "examples/fifo_sync/fifo_sync.sv:27.32-27.38" *) empty;
  assign _008_ = rd_ptr[3] ? _052_ : _051_;
  assign _051_ = rd_ptr[2] ? _054_ : _053_;
  assign _052_ = rd_ptr[2] ? _056_ : _055_;
  assign _053_ = rd_ptr[1] ? _058_ : _057_;
  assign _054_ = rd_ptr[1] ? _060_ : _059_;
  assign _055_ = rd_ptr[1] ? _062_ : _061_;
  assign _056_ = rd_ptr[1] ? _064_ : _063_;
  assign _057_ = rd_ptr[0] ? \mem[1]  : \mem[0] ;
  assign _058_ = rd_ptr[0] ? \mem[3]  : \mem[2] ;
  assign _059_ = rd_ptr[0] ? \mem[5]  : \mem[4] ;
  assign _060_ = rd_ptr[0] ? \mem[7]  : \mem[6] ;
  assign _061_ = rd_ptr[0] ? \mem[9]  : \mem[8] ;
  assign _062_ = rd_ptr[0] ? \mem[11]  : \mem[10] ;
  assign _063_ = rd_ptr[0] ? \mem[13]  : \mem[12] ;
  assign _064_ = rd_ptr[0] ? \mem[15]  : \mem[14] ;
  assign _065_ = _019_ & _041_;
  assign _066_ = _034_ & _041_;
  assign _067_ = _035_ & _041_;
  assign _068_ = _037_ & _041_;
  assign _069_ = _038_ & _041_;
  assign _070_ = _039_ & _041_;
  assign _071_ = _040_ & _041_;
  assign _072_ = _021_ & _041_;
  assign _073_ = _023_ & _041_;
  assign _074_ = _025_ & _041_;
  assign _075_ = _027_ & _041_;
  assign _076_ = _028_ & _041_;
  assign _077_ = _029_ & _041_;
  assign _078_ = _030_ & _041_;
  assign _079_ = _032_ & _041_;
  assign _080_ = _033_ & _041_;
  assign _082_ = _015_ ? (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:53.20-53.20|examples/fifo_sync/fifo_sync.sv:36.13-70.20" *) _081_ : 4'hx;
  assign _081_ = _048_ ? (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:48.25-48.57|examples/fifo_sync/fifo_sync.sv:48.21-51.49" *) 4'h0 : _011_;
  assign _086_ = _016_ ? (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:53.20-53.20|examples/fifo_sync/fifo_sync.sv:36.13-70.20" *) _085_ : 4'hx;
  assign _085_ = _047_ ? (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:39.25-39.57|examples/fifo_sync/fifo_sync.sv:39.21-42.49" *) 4'h0 : _009_;
  function [4:0] _191_;
    input [4:0] a;
    input [9:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "examples/fifo_sync/fifo_sync.sv:44.20-44.20|examples/fifo_sync/fifo_sync.sv:36.13-70.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _191_ = b[4:0];
      2'b1?:
        _191_ = b[9:5];
      default:
        _191_ = a;
    endcase
  endfunction
  assign _088_ = _191_(5'hxx, { _010_, _089_ }, { _087_, _084_ });
  assign _087_ = { do_write, do_read } == (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:36.39-36.39|examples/fifo_sync/fifo_sync.sv:36.13-70.20" *) 2'h2;
  assign _083_ = { do_write, do_read } == (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:53.20-53.20|examples/fifo_sync/fifo_sync.sv:36.13-70.20" *) 2'h3;
  assign _084_ = { do_write, do_read } == (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:44.20-44.20|examples/fifo_sync/fifo_sync.sv:36.13-70.20" *) 2'h1;
  assign _005_[0] = _087_ ? (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:36.39-36.39|examples/fifo_sync/fifo_sync.sv:36.13-70.20" *) 1'h1 : 1'h0;
  assign _004_ = _087_ ? (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:36.39-36.39|examples/fifo_sync/fifo_sync.sv:36.13-70.20" *) data_in : 8'hxx;
  assign _007_[0] = _083_ ? (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:53.20-53.20|examples/fifo_sync/fifo_sync.sv:36.13-70.20" *) 1'h1 : 1'h0;
  assign _006_ = _083_ ? (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:53.20-53.20|examples/fifo_sync/fifo_sync.sv:36.13-70.20" *) data_in : 8'hxx;
  assign _003_[0] = rst ? (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:30.13-30.16|examples/fifo_sync/fifo_sync.sv:30.9-71.12" *) 1'h0 : _007_[0];
  assign _002_ = rst ? (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:30.13-30.16|examples/fifo_sync/fifo_sync.sv:30.9-71.12" *) 8'hxx : _006_;
  assign _001_[0] = rst ? (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:30.13-30.16|examples/fifo_sync/fifo_sync.sv:30.9-71.12" *) 1'h0 : _005_[0];
  assign _000_ = rst ? (* full_case = 32'd1 *) (* src = "examples/fifo_sync/fifo_sync.sv:30.13-30.16|examples/fifo_sync/fifo_sync.sv:30.9-71.12" *) 8'hxx : _004_;
  assign _089_ = count - (* src = "examples/fifo_sync/fifo_sync.sv:52.30-52.42" *) 1'h1;
  assign _005_[7:1] = { _005_[0], _005_[0], _005_[0], _005_[0], _005_[0], _005_[0], _005_[0] };
  assign _003_[7:1] = { _003_[0], _003_[0], _003_[0], _003_[0], _003_[0], _003_[0], _003_[0] };
  assign _001_[7:1] = { _001_[0], _001_[0], _001_[0], _001_[0], _001_[0], _001_[0], _001_[0] };
  assign _007_[7:1] = { _007_[0], _007_[0], _007_[0], _007_[0], _007_[0], _007_[0], _007_[0] };
endmodule
